apiVersion: v1
kind: Service
metadata:
  name: expensetracker-frontend-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: expensetracker-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
