apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker-frontend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: expensetracker-frontend
  template:
    metadata:
      labels:
        app: expensetracker-frontend
    spec:
      containers:
      - name: expensetracker-frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
