apiVersion: v1
kind: ConfigMap
metadata:
  name: expensetracker-config
  namespace: {{ .Values.namespace }}
data:
  AZURE_SQL_SERVER: {{ .Values.config.azureSqlServer | quote }}
  AZURE_SQL_DB: {{ .Values.config.azureSqlDb | quote }}
