apiVersion: v1
kind: Secret
metadata:
  name: expensetracker-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AZURE_SQL_USER: {{ .Values.secret.azureSqlUser | quote }}
  AZURE_SQL_PASSWORD: {{ .Values.secret.azureSqlPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
