replicaCount: 1

image:
  repository: somanathmuduli03/expensetracker
  tag: "1.4"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

namespace: dev

ingress:
  host: api.afet.online
  tlsSecretName: api-afet-tls

config:
  azureSqlServer: "apet-sql.database.windows.net"
  azureSqlDb: "apet-small"

secret:
  azureSqlUser: "mysqladmin"
  azureSqlPassword: ""
  jwtSecret: ""
