namespace: qa

ingress:
  host: api-qa.afet.online
  tlsSecretName: api-qa-afet-tls

image:
  tag: "qa-latest"

replicaCount: 1

config:
  azureSqlServer: "apet-sql.database.windows.net"
  azureSqlDb: "apet-small"
