namespace: qa

ingress:
  host: api-qa.afet.online
  tlsSecretName: api-qa-afet-tls

image:
  tag: "1.4"

replicaCount: 1

config:
  azureSqlServer: "et-db.database.windows.net"
  azureSqlDb: "free-sql-db-3281680"
