apiVersion: v1
kind: Secret
metadata:
  name: expensetracker-secret
type: Opaque
stringData:
  AZURE_SQL_USER: "azureuser@et-db"
  AZURE_SQL_PASSWORD: "Mywish@94"
  JWT_SECRET: "MLEUmqf2HmdMGnTIukPpLDKeITZw2ofmTMyFIV2kS04="
